<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Comprobar</name>
   <tag></tag>
   <elementGuidId>0457fff4-c047-4269-bc28-9791c35c162e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#check-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='check-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6135939d-08a6-4ed0-bd33-e051c5a4c19f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-check</value>
      <webElementGuid>4d3ca32a-1dfd-4d0e-87b2-b22efbafad69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>check-button</value>
      <webElementGuid>e1ec87b3-a277-4028-a5c1-6795ba8c80ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>ca6e565a-7019-490c-bdc6-49160d653f71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Comprobar</value>
      <webElementGuid>0193e36c-2eff-4d48-89e0-3ab4188e37d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;check-button&quot;)</value>
      <webElementGuid>c2baac99-d301-4c07-ae7b-3e840aab17cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6bc874d9-0815-4272-9a47-d216dbe3cdf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-check</value>
      <webElementGuid>9713b2a2-7816-4289-844e-619d58d51962</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>check-button</value>
      <webElementGuid>d15add1a-70b4-47cf-9838-cd482779bfdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>c6c71582-14e1-430a-9439-a08e08db4f2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Comprobar</value>
      <webElementGuid>f33a9dc8-48ab-4811-a081-52e4b5d8a311</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;check-button&quot;)</value>
      <webElementGuid>2e3e8e27-339b-46b1-aa31-8758a09d88e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c05e69c8-b4f3-485f-90f5-e7006ac0e809</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-check</value>
      <webElementGuid>d658adf9-18d4-4e50-9cb7-5aa53931930b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>check-button</value>
      <webElementGuid>cce61715-4792-4a16-9eae-9dae5c5cd85f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>56a07493-7ac6-43e5-a239-2157de202b07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Comprobar</value>
      <webElementGuid>07e803e0-6dd3-400c-bc44-cac2c141e365</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;check-button&quot;)</value>
      <webElementGuid>57f9eda2-76df-483d-b8bb-02b7aadc1669</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a7f9c113-f331-4432-82a3-11dada8e2be5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-check</value>
      <webElementGuid>16d2eef4-1ad1-46ca-9a7d-83499d6566bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>check-button</value>
      <webElementGuid>b79190a9-1b08-4d92-a2ef-fb1f3df04ab7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>afb267b4-48b6-446f-aae6-0e3adc1672c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Comprobar</value>
      <webElementGuid>ea0c0e0b-d4d6-4de8-aee8-2dabb0711aff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;check-button&quot;)</value>
      <webElementGuid>1ef8ee23-693a-43e2-81c5-f7d5f5398461</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='check-button']</value>
      <webElementGuid>54077d07-e9d3-41f3-a13c-e4f4fbdaff62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Comprobar DNI, NIE o CIF españoles de acuerdo con la normativa vigente'])[1]/following::button[1]</value>
      <webElementGuid>bc355ae5-b7da-4642-8e0a-0f352a853750</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'check-button', '&quot;', ')')])[1]/preceding::button[1]</value>
      <webElementGuid>346e3135-3bda-4363-b573-3330b646733e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Comprobar']/parent::*</value>
      <webElementGuid>87ba8cf7-0c57-40ae-8103-6c5f1e23efe0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>13a7447c-02a7-41e1-ade5-f599e2d8a3f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'check-button' and @type = 'submit' and (text() = 'Comprobar' or . = 'Comprobar')]</value>
      <webElementGuid>4382ad9e-bb32-49e0-949e-ecc1a799b928</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
