<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Comprobar DNI, NIE o CIF espaoles de _0d1816</name>
   <tag></tag>
   <elementGuidId>6286ff79-8606-4c48-aed4-cc9b1a4572fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nif</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nif']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>392458c4-ae8a-49b7-a044-f89cf39fe850</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nif</value>
      <webElementGuid>f8d1cea7-371a-4cf6-aa55-83e3c0bcd092</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>nif</value>
      <webElementGuid>d737fdeb-0361-464b-9e38-43d76f539169</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nif uppercase</value>
      <webElementGuid>302910e3-1a12-41c1-9453-75fb48e24381</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>DNI, NIE, CIF</value>
      <webElementGuid>cddcba16-3886-47f4-be99-600c01d36f78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nif</value>
      <webElementGuid>9d6a9e81-ace1-43b5-a10f-9cedf1abb2a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>2a39f6b8-62d9-42b1-b2e6-cb8c67d9e64e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nif&quot;)</value>
      <webElementGuid>dcf9c831-9737-455e-a726-d8e06a8b6b4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ea6b1bf4-3f5a-4d97-b558-fe68264269a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nif</value>
      <webElementGuid>c5d92e82-47e0-4266-a1fe-f56a01232684</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>nif</value>
      <webElementGuid>43a4f78d-b184-4c6a-9834-0ea0aa56353e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nif uppercase</value>
      <webElementGuid>b5ab4dce-7025-4f2d-acd9-2115a2e2f34a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>DNI, NIE, CIF</value>
      <webElementGuid>06d1bed1-bef4-4c9d-8dcc-5e0226f10ebc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nif</value>
      <webElementGuid>c1c52fc8-bfeb-413b-97e9-587c53fd6a5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>39a60f78-904c-46a5-bfd2-50bcf66e1a5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nif&quot;)</value>
      <webElementGuid>01bbe68d-3d45-4615-a866-4f3dc9385a4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e8705b7d-b3b0-4ea4-9bac-19b68a4bf55c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nif</value>
      <webElementGuid>bb41d6e5-a524-483e-a26e-182b8065f4f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>nif</value>
      <webElementGuid>d02bad24-bb30-4f9f-8119-bb6020f64f18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nif uppercase</value>
      <webElementGuid>73ff6374-fbcc-424c-aa53-de295b84c29a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>DNI, NIE, CIF</value>
      <webElementGuid>f194e623-19c8-48aa-b063-e9250ac83031</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nif</value>
      <webElementGuid>39ed5d5c-bdb1-48b5-8fc5-a74363fb1af3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>fb5f32ac-a47a-4cc3-89e8-b195ccb13d1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nif&quot;)</value>
      <webElementGuid>63b8e980-1ba3-4dce-b8a9-c4801221e0c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>80bd6278-0ca4-4aba-aa27-99cd28c79d0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nif</value>
      <webElementGuid>fe5d41f0-0ea2-4295-b303-cf1e7a71cfb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>nif</value>
      <webElementGuid>0aa523da-36b4-49bf-a066-26bec45bb11d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nif uppercase</value>
      <webElementGuid>4850466d-f53b-4b95-94f7-48a22e02f046</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>DNI, NIE, CIF</value>
      <webElementGuid>f401a5cc-56cb-421a-a754-a971a4ed5118</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nif</value>
      <webElementGuid>43b7b47e-906b-4905-a7b3-5ed78325a7c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>79541974-fbfe-4cd5-8c1f-bccc9abd11e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nif&quot;)</value>
      <webElementGuid>d0edbdbd-2c7a-48c4-9cea-94351d11caf3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nif']</value>
      <webElementGuid>5a490a54-3e7b-4262-ad9f-58c1f2e87da8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>b887f801-5104-4d87-96d2-8690bdc6ac88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'nif' and @type = 'nif' and @placeholder = 'DNI, NIE, CIF' and @name = 'nif']</value>
      <webElementGuid>412856d4-9ae9-4df3-9177-a4248c6b1211</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
